# Set the path to the Starship config file
export STARSHIP_CONFIG="{{cookiecutter.STARSHIP_CONFIG}}"

export ZSH="{{cookiecutter.OH_MY_ZSH_DIR}}"

# Init starship
eval "$(starship init zsh)"

# Function to set title
function set_win_title(){
    echo -ne "\033]0; $USER@$HOST:${PWD/$HOME/~} \007"
}
precmd_functions+=(set_win_title)

# Follow color schemes generated by pywal
(cat "{{cookiecutter.CACHE_DIR}}/wal/sequences" &)

## Plugins section: Enable fish style features
# Use syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Use autosuggestion
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Use history substring search
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# Use fzf
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh


# Replace ls with exa
alias ls='exa -al --color=always --group-directories-first --icons' # preferred listing
alias la='exa -a --color=always --group-directories-first --icons'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first --icons'  # long format
alias lt='exa -aT --color=always --group-directories-first --icons' # tree listing
alias l.='exa -ald --color=always --group-directories-first --icons .*' # show only dotfiles

# Cat
alias cat='bat --style header --style snip --style changes --style header'

# NVM
# Set NVM directory to custom path
export NVM_DIR="{{cookiecutter.NVM_DIR}}"

# Load NVM if it exists
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Load NVM bash completion (optional)
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
