#!/bin/bash

: '
     __ __     ____           __        ____               __ __
  __/ // /_   /  _/___  _____/ /_____ _/ / /__  _____   __/ // /_
 /_  _  __/   / // __ \/ ___/ __/ __ `/ / / _ \/ ___/  /_  _  __/
/_  _  __/  _/ // / / (__  ) /_/ /_/ / / /  __/ /     /_  _  __/
 /_//_/    /___/_/ /_/____/\__/\__,_/_/_/\___/_/       /_//_/

'

# ------------------ Source relevant variables/constants and functions ------------------ #
this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

lib_scripts="$this_dir/src/.lib/export.sh"
configs="$this_dir/src/.conf/export.sh"
settings="$this_dir/settings"

# Settings needs to be sourced first because it contains definitions required by settings at config directory.
source $settings
source $configs
source $lib_scripts
# --------------------------------------------------------------------------------------- #


# ------------------------------------ Setup ------------------------------------ #
clear # Clear the terminal for clearer output.
check_distro "$SUPPORTED_DISTROS" # Check if the current distro is supported.
parse_options "$@" # Parse the comand line options.
pretty_print_installer_msg # Pretty print the installer message.
prompt_install # Promp for proceeding with installation.
check_and_install_utilities "$TEMP_DOTFILES_INSTALL_PATH" "${UTILS_REPOS[@]}" # Install utilities required for installation.
create_log # Create file for logging the installation (if enabled)
check_previous_installation # Check for previous installation
show_install_type # Show the installation type to be performed
install_pacman_packages "$PREREQUISITES" # Install dependencies for installation
install_yay
exit 0

# --------------------------------------------------------------------------------------- #


# ------------------------------------ Install ------------------------------------ #
tasks() {

   install_pacman_packages "$PACMAN_PACKAGES"
   install_yay_packages "$YAY_PACKAGES"
   install_pyenv "$TEMP_PYENV_INSTALL_PATH"
   install_python_version "$TEMP_PYENV_INSTALL_PATH" "$PYTHON_VERSION"
   #create_python_venv "$TEMP_DEPENDENCIES_INSTALL_PATH/python_venv"
   #install_packages_in_venv "$PIP_PACKAGES" "$TEMP_DEPENDENCIES_INSTALL_PATH/python_venv"
   #install_vcpkg "$TEMP_DEPENDENCIES_INSTALL_PATH/vcpkg"
   #install_date_h "$TEMP_DEPENDENCIES_INSTALL_PATH/vcpkg"

   #create_dirs "$INSTALL_PATH" "$DEPENDENCIES_INSTALL_PATH"
   #mv "$TEMP_DEPENDENCIES_INSTALL_PATH/vcpkg" "$VCPKG_INSTALL_DIR"

}

tasks

# --------------------------------------------------------------------------------------- #


$print_debug "Installation finished!!!" -t "info"
if [ "$ENABLE_LOG" == "true" ] && [ "$ENABLE_DEBUG" == "true" ]; then
   print "Installation log generated at '$LOG'."
fi
exit 0