export SELECTED_WAYBAR_THEME_VAR="selected_waybar_theme"
export CURRENT_WAYBAR_THEME_VAR="current_waybar_theme"
export ROFI_SELECTED_WALLPAPER_VAR="selected_wallpaper"
export ROFI_CURRENT_WALLPAPER_VAR="current_wallpaper"
export ROFI_CURRENT_WALLPAPER_NAME_VAR="current_wallpaper_name"
export ROFI_SELECTED_WALLPAPER_EFFECT_VAR="selected_wallpaper_effect"
export ROFI_CURRENT_WALLPAPER_EFFECT_VAR="current_wallpaper_effect"
export CUSTOM_WALLPAPER_DIR_VAR="custom_wallpaper_dir"
export WALLPAPER_BLUR_VAR="wallpaper_blur"
export WALLPAPER_BRIGHTNESS_VAR="wallpaper_brightness"
export CACHED_WALLPAPER_EFFECTS_VAR="cached_wallpapers"
export WAYBAR_CURRENT_LAUNCH_COMMAND_VAR="waybar_launch_command"
export WAYBAR_CURRENT_STATUS_VAR="waybar_current_status"




export ROFI_WALLPAPER_SELECTOR_WINDOW_NAME="Wallpaper"
